# Generated by Django 4.0.5 on 2022-06-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogtagindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
